# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simon/SyncData/Code-Store/c-code/acroman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simon/SyncData/Code-Store/c-code/acroman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/SyncData/Code-Store/c-code/acroman/CMakeFiles /home/simon/SyncData/Code-Store/c-code/acroman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/SyncData/Code-Store/c-code/acroman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named amt

# Build rule for target.
amt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 amt
.PHONY : amt

# fast build rule for target.
amt/fast:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/build
.PHONY : amt/fast

amt-db-funcs.o: amt-db-funcs.c.o

.PHONY : amt-db-funcs.o

# target to build an object file
amt-db-funcs.c.o:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/amt-db-funcs.c.o
.PHONY : amt-db-funcs.c.o

amt-db-funcs.i: amt-db-funcs.c.i

.PHONY : amt-db-funcs.i

# target to preprocess a source file
amt-db-funcs.c.i:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/amt-db-funcs.c.i
.PHONY : amt-db-funcs.c.i

amt-db-funcs.s: amt-db-funcs.c.s

.PHONY : amt-db-funcs.s

# target to generate assembly for a file
amt-db-funcs.c.s:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/amt-db-funcs.c.s
.PHONY : amt-db-funcs.c.s

cli-args.o: cli-args.c.o

.PHONY : cli-args.o

# target to build an object file
cli-args.c.o:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/cli-args.c.o
.PHONY : cli-args.c.o

cli-args.i: cli-args.c.i

.PHONY : cli-args.i

# target to preprocess a source file
cli-args.c.i:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/cli-args.c.i
.PHONY : cli-args.c.i

cli-args.s: cli-args.c.s

.PHONY : cli-args.s

# target to generate assembly for a file
cli-args.c.s:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/cli-args.c.s
.PHONY : cli-args.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/main.c.s
.PHONY : main.c.s

sqlite3.o: sqlite3.c.o

.PHONY : sqlite3.o

# target to build an object file
sqlite3.c.o:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/sqlite3.c.o
.PHONY : sqlite3.c.o

sqlite3.i: sqlite3.c.i

.PHONY : sqlite3.i

# target to preprocess a source file
sqlite3.c.i:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/sqlite3.c.i
.PHONY : sqlite3.c.i

sqlite3.s: sqlite3.c.s

.PHONY : sqlite3.s

# target to generate assembly for a file
sqlite3.c.s:
	$(MAKE) -f CMakeFiles/amt.dir/build.make CMakeFiles/amt.dir/sqlite3.c.s
.PHONY : sqlite3.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... amt"
	@echo "... amt-db-funcs.o"
	@echo "... amt-db-funcs.i"
	@echo "... amt-db-funcs.s"
	@echo "... cli-args.o"
	@echo "... cli-args.i"
	@echo "... cli-args.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sqlite3.o"
	@echo "... sqlite3.i"
	@echo "... sqlite3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

