name: amt-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt -y autoremove
        sudo apt -y install build-essential cmake readline-common libreadline-dev
    - name: Create build CMake
      run: |
        ./build.sh
    - name : Test Run 'amt' App
      run: |
        cd bin/
        ./amt -h
        ./amt
